Repository ezlint/ezlint, pull requests merged in 2020-09, with the labels that each got.

#19 Themeprovider for the material UI component
  .eslintrc.js
  CODE_OF_CONDUCT.md
  README.md
  package.json
  public/index.html
  src/App.tsx
  src/lib/interfaces/eslint-config-partial.d.ts
  src/lib/interfaces/library-config.d.ts
  src/lib/partial-builder.spec.ts
  src/lib/partial-builder.ts
  src/serviceWorker.ts
  template/conf-template.json
  template/example.json
  tsconfig.json
Labels: enhancement

#37 Improve the home page layout
  src/components/organisms/SearchThingy.tsx
  src/components/pages/Home.tsx
  src/components/templates/Layout.tsx
Labels: enhancement

#36 Add optional extends logic
  src/lib/eslint-config-partial-builder.spec.ts
  src/lib/eslint-config-partial-builder.ts
  src/lib/interfaces/intermediate-config-collector.d.ts
  src/lib/intermediate-config-collector-builder.spec.ts
  src/lib/intermediate-config-collector-builder.ts
Labels: enhancement

#38 Rename libs' plugins
  src/lib/plugins/index.ts
  src/lib/plugins/jest.ts
  src/lib/plugins/prettier.ts
  src/lib/plugins/react-hooks.ts
  src/lib/plugins/react.ts
  src/lib/plugins/typescript.ts
Labels: bug

#42 [chore] add shields to readme
  README.md
Labels: documentation

#33 Refactor results page to use components
  src/components/molecules/CommandDisplay.tsx
  src/components/molecules/ConfigDisplay.tsx
  src/components/pages/Results.tsx
Labels: enhancement

#40 [chore] add community files
  .github/ISSUE_TEMPLATE/add-a-new-library.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
Labels: documentation, enhancement
